package com.tts.web.nms.model;
// Generated Jun 23, 2016 1:48:44 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Slatasklevel generated by hbm2java
 */
@Entity
@Table(name = "slatasklevel", catalog = "SRMSDB")
public class Slatasklevel implements java.io.Serializable {

	private Integer slaid;
	private Issuesolutioncategorymap issuesolutioncategorymap;
	private Usergroup usergroupByGroupFrom;
	private Usergroup usergroupByGroupTo;
	private String vipsla;
	private String bscodeOrStar;
	private String loyltyIndicator;
	private int slahour;
	private String slatype;
	private String createdby;
	private Date createddate;
	private String updatedby;
	private Date updateddate;

	public Slatasklevel() {
	}

	public Slatasklevel(Issuesolutioncategorymap issuesolutioncategorymap, Usergroup usergroupByGroupFrom,
			Usergroup usergroupByGroupTo, int slahour, String slatype) {
		this.issuesolutioncategorymap = issuesolutioncategorymap;
		this.usergroupByGroupFrom = usergroupByGroupFrom;
		this.usergroupByGroupTo = usergroupByGroupTo;
		this.slahour = slahour;
		this.slatype = slatype;
	}

	public Slatasklevel(Issuesolutioncategorymap issuesolutioncategorymap, Usergroup usergroupByGroupFrom,
			Usergroup usergroupByGroupTo, String vipsla, String bscodeOrStar, String loyltyIndicator, int slahour,
			String slatype, String createdby, Date createddate, String updatedby, Date updateddate) {
		this.issuesolutioncategorymap = issuesolutioncategorymap;
		this.usergroupByGroupFrom = usergroupByGroupFrom;
		this.usergroupByGroupTo = usergroupByGroupTo;
		this.vipsla = vipsla;
		this.bscodeOrStar = bscodeOrStar;
		this.loyltyIndicator = loyltyIndicator;
		this.slahour = slahour;
		this.slatype = slatype;
		this.createdby = createdby;
		this.createddate = createddate;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SLAID", unique = true, nullable = false)
	public Integer getSlaid() {
		return this.slaid;
	}

	public void setSlaid(Integer slaid) {
		this.slaid = slaid;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "IssueSolutionCategoryMapID", nullable = false)
	public Issuesolutioncategorymap getIssuesolutioncategorymap() {
		return this.issuesolutioncategorymap;
	}

	public void setIssuesolutioncategorymap(Issuesolutioncategorymap issuesolutioncategorymap) {
		this.issuesolutioncategorymap = issuesolutioncategorymap;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "GroupFrom", nullable = false)
	public Usergroup getUsergroupByGroupFrom() {
		return this.usergroupByGroupFrom;
	}

	public void setUsergroupByGroupFrom(Usergroup usergroupByGroupFrom) {
		this.usergroupByGroupFrom = usergroupByGroupFrom;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "GroupTo", nullable = false)
	public Usergroup getUsergroupByGroupTo() {
		return this.usergroupByGroupTo;
	}

	public void setUsergroupByGroupTo(Usergroup usergroupByGroupTo) {
		this.usergroupByGroupTo = usergroupByGroupTo;
	}

	@Column(name = "VIPSLA", length = 100)
	public String getVipsla() {
		return this.vipsla;
	}

	public void setVipsla(String vipsla) {
		this.vipsla = vipsla;
	}

	@Column(name = "BSCodeOrStar", length = 100)
	public String getBscodeOrStar() {
		return this.bscodeOrStar;
	}

	public void setBscodeOrStar(String bscodeOrStar) {
		this.bscodeOrStar = bscodeOrStar;
	}

	@Column(name = "LoyltyIndicator", length = 100)
	public String getLoyltyIndicator() {
		return this.loyltyIndicator;
	}

	public void setLoyltyIndicator(String loyltyIndicator) {
		this.loyltyIndicator = loyltyIndicator;
	}

	@Column(name = "SLAHour", nullable = false)
	public int getSlahour() {
		return this.slahour;
	}

	public void setSlahour(int slahour) {
		this.slahour = slahour;
	}

	@Column(name = "SLAType", nullable = false, length = 20)
	public String getSlatype() {
		return this.slatype;
	}

	public void setSlatype(String slatype) {
		this.slatype = slatype;
	}

	@Column(name = "Createdby", length = 100)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Createddate", length = 19)
	public Date getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	@Column(name = "Updatedby", length = 100)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Updateddate", length = 19)
	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

}
