package com.tts.web.nms.model;
// Generated Jun 5, 2016 4:28:34 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ticketlockunlockdetails generated by hbm2java
 */
@Entity
@Table(name = "ticketlockunlockdetails", catalog = "SRMSDB")
public class Ticketlockunlockdetails implements java.io.Serializable {

	private Integer ticketLockUnlockId;
	private Integer ticketHopsId;
	private Date activityDate;
	private String flag;
	private String activityBy;

	public Ticketlockunlockdetails() {
	}

	public Ticketlockunlockdetails(Integer ticketHopsId, Date activityDate, String flag, String activityBy) {
		this.ticketHopsId = ticketHopsId;
		this.activityDate = activityDate;
		this.flag = flag;
		this.activityBy = activityBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "TicketLockUnlockId", unique = true, nullable = false)
	public Integer getTicketLockUnlockId() {
		return this.ticketLockUnlockId;
	}

	public void setTicketLockUnlockId(Integer ticketLockUnlockId) {
		this.ticketLockUnlockId = ticketLockUnlockId;
	}

	@Column(name = "TicketHopsId")
	public Integer getTicketHopsId() {
		return this.ticketHopsId;
	}

	public void setTicketHopsId(Integer ticketHopsId) {
		this.ticketHopsId = ticketHopsId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ActivityDate", length = 19)
	public Date getActivityDate() {
		return this.activityDate;
	}

	public void setActivityDate(Date activityDate) {
		this.activityDate = activityDate;
	}

	@Column(name = "Flag", length = 100)
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	@Column(name = "ActivityBy", length = 100)
	public String getActivityBy() {
		return this.activityBy;
	}

	public void setActivityBy(String activityBy) {
		this.activityBy = activityBy;
	}

}
