package com.tts.web.nms.model;
// Generated Jun 5, 2016 4:28:34 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ticketcomments generated by hbm2java
 */
@Entity
@Table(name = "ticketcomments", catalog = "SRMSDB")
public class Ticketcomments implements java.io.Serializable {

	private Integer ticketCommentsId;
	private Tickethops tickethops;
	private String ticketNumber;
	private String comments;
	private String createdby;
	private Date createddate;
	private String updatedby;
	private Date updateddate;

	public Ticketcomments() {
	}

	public Ticketcomments(Tickethops tickethops, String ticketNumber, String comments, String createdby,
			Date createddate, String updatedby, Date updateddate) {
		this.tickethops = tickethops;
		this.ticketNumber = ticketNumber;
		this.comments = comments;
		this.createdby = createdby;
		this.createddate = createddate;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "TicketCommentsID", unique = true, nullable = false)
	public Integer getTicketCommentsId() {
		return this.ticketCommentsId;
	}

	public void setTicketCommentsId(Integer ticketCommentsId) {
		this.ticketCommentsId = ticketCommentsId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "TicketHopsID")
	public Tickethops getTickethops() {
		return this.tickethops;
	}

	public void setTickethops(Tickethops tickethops) {
		this.tickethops = tickethops;
	}

	@Column(name = "TicketNumber", length = 100)
	public String getTicketNumber() {
		return this.ticketNumber;
	}

	public void setTicketNumber(String ticketNumber) {
		this.ticketNumber = ticketNumber;
	}

	@Column(name = "Comments", length = 1000)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Column(name = "Createdby", length = 100)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Createddate", length = 19)
	public Date getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	@Column(name = "Updatedby", length = 100)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Updateddate", length = 19)
	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

}
