package com.tts.web.nms.model;
// Generated Sep 1, 2016 8:41:52 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usergroupbusinessprocessmap generated by hbm2java
 */
@Entity
@Table(name = "usergroupbusinessprocessmap", catalog = "SRMSDB")
public class Usergroupbusinessprocessmap implements java.io.Serializable {

	private Integer userGroupBusinessProcessId;
	private Businessprocess businessprocess;
	private Usergroup usergroup;
	private String active;
	private String createdBy;
	private Date createdDate;
	private String updatedBy;
	private Date updatedDate;

	public Usergroupbusinessprocessmap() {
	}

	public Usergroupbusinessprocessmap(Businessprocess businessprocess, Usergroup usergroup, String active,
			String createdBy, Date createdDate, String updatedBy, Date updatedDate) {
		this.businessprocess = businessprocess;
		this.usergroup = usergroup;
		this.active = active;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "UserGroupBusinessProcessID", unique = true, nullable = false)
	public Integer getUserGroupBusinessProcessId() {
		return this.userGroupBusinessProcessId;
	}

	public void setUserGroupBusinessProcessId(Integer userGroupBusinessProcessId) {
		this.userGroupBusinessProcessId = userGroupBusinessProcessId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "BusinessProcessID")
	public Businessprocess getBusinessprocess() {
		return this.businessprocess;
	}

	public void setBusinessprocess(Businessprocess businessprocess) {
		this.businessprocess = businessprocess;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "UserGroupID")
	public Usergroup getUsergroup() {
		return this.usergroup;
	}

	public void setUsergroup(Usergroup usergroup) {
		this.usergroup = usergroup;
	}

	@Column(name = "Active", length = 20)
	public String getActive() {
		return this.active;
	}

	public void setActive(String active) {
		this.active = active;
	}

	@Column(name = "CreatedBy", length = 100)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedDate", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "UpdatedBy", length = 100)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UpdatedDate", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
